name: LSDtools
main: LSDtools.LSDtools
version: 0.2
author: LSDog
commands:
  LSDtools:
    description: Info of LSDtools
    permission: "LSDtools.info"
    permission-message: "§7无权限 (LSDtools.info)"

  LSDtools reload:
    description: Info of LSDtools
    permission: "LSDtools.reload"
    permission-message: "§7无权限 (LSDtools.reload)"

  checkplayer:
    description: Check one's ip
    permission: "LSDtools.check"
    permission-message: "§7无权限 (LSDtools.check)"

  gettools:
    description: gettools
    permission: "LSDtools.tools"
    permission-message: "§7无权限 (LSDtools.tools)"

  lore:
    description: about lore
    permission: "LSDtools.lore"
    permission-message: "§7无权限 (LSDtools.lore)"

  signedit:
    description: edit a sign
    permission: "LSDtools.signedit"
    permission-message: "§7无权限 (LSDtools.signedit)"
