#LSDtools config
#Plugin version : 0.37

#请勿乱动
version: 0.3

#玩家加入时向控制台发送消息 (默认:true)
joinInfoConsole: true
#玩家加入时向OP或用有权限"LSDtools.check"的人发送消息 (默认:true)
joinInfoOP: true

#限制同一IP下最多有几个账号, 0=无限制
MostAccountWithSameIP: 0

#是否启用烦人的AI"sabi" (默认:true)
AI: true
