name: LSDtools
main: LSDtools.LSDtools
version: 0.2
author: LSDog
commands:
  LSDtools:
    description: Info of LSDtools
#    usage: /LSDtools
#    aliases: []
    permission: "LSDtools.info"
    permission-message: "§7无权限 (LSDtools.info)"
  checkplayer:
    description: Check one's ip
#    usage: /checkplayer <player>
#    aliases: []
    permission: "LSDtools.check"
    permission-message: "§7无权限 (LSDtools.check)"
  checkplayers:
    description: Check all player's ip
#    usage: /checkplayers
#    aliases: []
    permission: "LSDtools.check"
    permission-message: "§7无权限 (LSDtools.check)"