name: LSDtools
main: LSDtools.LSDtools
version: 0.2
author: LSDog
commands:
  LSDtools:
    description: Info of LSDtools
    permission: "LSDtools.info"
    permission-message: "§7无权限 (LSDtools.info)"

  LSDtools reload:
    description: Info of LSDtools
    permission: "LSDtools.reload"
    permission-message: "§7无权限 (LSDtools.reload)"

  checkplayer:
    description: Check one's ip
    permission: "LSDtools.check"
    permission-message: "§7无权限 (LSDtools.check)"

  checkplayers:
    description: Check all player's ip
    permission: "LSDtools.check"

  gettools:
    description: gettools
    permission: "LSDtools.tools"
    permission-message: "§7无权限 (LSDtools.tools)"