name: LSDtools
main: LSDtools.LSDtools
version: 0.1
author: LSDog
commands:
  LSDtools:
    description: Info of LSDtools
    usage: /LSDtools
    aliases: []
    permission: "LSDtools.info"
    permission-message: "no permission ;-;"
  checkplayers:
    description: Check player's ip
    usage: /checkplayers
    aliases: []
    permission: "LSDtools.check"
    permission-message: "no permission ;-;"